### ISSUE TITLE
Unable to find the exact direction route

### ISSUE THREAD

**Issue by SharfMohiuddin** [vvivan89/react-native-maps-arrow-line#1] opened 2022-11-16 14:20 UTC
Hi there,

The markers on the polyline are not pointing the right direction on the route as these markers are rotating as the user rotates the map. Is there any way to put these markers in the right direction according to the heading direction from the DB? Thanks!

**Comment by vvivan89** [comment] 2022-11-17 19:27
Fixed in v0.2.0, please refer to the change log and updated README.
The usage of the component has to be updated in order to fix the issue - instead of MapView, you will have to use the component from this package.

Arrows will follow map rotation with a slight but visible delay. This is caused by the asynchronous nature of the getCamera method of MapView component. I don't see how this can be improved at the moment.

**Closed as completed by vvivan89** 2022-11-17 19:27 UTC
